### ISSUE TITLE
zcat$f should be zcat $f

### ISSUE THREAD

**Issue by themaddoctor** [mvertes/txt2man#13]
in bookman line 113:
(*.Z|*.gz) zcat$f;;

The space between zcat and $f is missing.

**Comment by mvertes** [comment]
Hello, thanks for the report and the fi!
Feel free to submit a pull request. For such a small change, you can probably do it directly from the web page.

**Comment by ttepatti** [comment]
Hello! Just a heads up, this is still an issue on the latest version of bookman available on the Debian repo (Bookman v1.5.6)

It appears to be fixed in this repository, but I figured I would let you know in case you were unaware. At this point, you can't use bookman after apt-get installing txt2man on Debian without making this zcat change.

Thanks for all of your hard work on this tool, by the way - it saved my butt when I wanted to print out and bind a physical copy of all of the manpages on my system :)

**Comment by mvertes** [comment]
Closing after release of txt2man-1.7.0
