### ISSUE TITLE
1.7.1: man pages gone

### ISSUE THREAD

**Issue by kloczek** [mvertes/txt2man#30]
Looks like there is no in git tree man pages.
Something went wrong?

**Comment by mvertes** [comment]
Manpages are not included with source files anymore, because they can be generated from sources (`make` command) and so the `make clean` command reverts the state of repository to the same one as just after extraction (see #16).

It is always possible to generate manpages with `make`. What is the problem to not have them present by default ?

**Comment by urbanjost** [comment]
A great utility. I had to tweek it just a bit to allow for Fortran manpages, where in the SYNTAX block it is more usual to say
        subroutine name(
or     function name(
instead of the C-like name(
syntax, but found it perfect for allowing people with no *roff knowledge to make manpages. In particular see
[Fortran Intrinsics manpages](https://github.com/urbanjost/fortran-intrinsic-manpages)

If would be nice if you supported Fortran descriptions in this way.  

Have you ever thought about adding an option to convert to HTML as well? I find that I often convert the manpages I generatre with your utility with groff(1) or manserver(1) into HTML and add a CSS style sheet to add them to webservers.
That process usually ends up generting rather poor HTML. Since you are already parsing the data to convert it to *roff sections which conform very nicely to HTML2 sections as well it would seem like a natural option to add.

Thanks for the great utility.
